# Generated by Django 4.2.30 on 2026-07-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestregistration',
            options={'ordering': ['guest_number']},
        ),
        migrations.AddField(
            model_name='guestregistration',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=30),
        ),
        migrations.AddField(
            model_name='guestregistration',
            name='guest_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='guestregistration',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='checkin.booking'),
        ),
        migrations.AlterField(
            model_name='guestregistration',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='guestregistration',
            unique_together={('booking', 'guest_number')},
        ),
    ]
