# Generated by Django 4.2.30 on 2026-07-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_alter_guestregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestregistration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestregistration',
            name='document_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='guestregistration',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='guestregistration',
            name='residence_address',
            field=models.TextField(blank=True),
        ),
    ]
