# Generated by Django 4.2.30 on 2026-07-09 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0007_add_webhookconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrequest',
            name='review_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
