# Generated by Django 4.2.30 on 2026-07-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_alter_reviewrequest_review_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='checkin.booking'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
