# Generated by Django 4.2.30 on 2026-05-08 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('plan', models.CharField(choices=[('basic', 'Basic – £29/month'), ('pro', 'Pro – £79/month')], default='basic', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=300)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=300)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_review', 'Pending Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_payment', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotel')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
