# Generated by Django 4.2.30 on 2026-05-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('invoice', 'Invoice / Pay Later'), ('stripe', 'Stripe Card')], default='bank_transfer', max_length=20),
        ),
    ]
