# Generated by Django 4.2.30 on 2026-05-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_registration_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
