# Generated by Django 4.2.30 on 2026-07-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_registration_payment_note_registration_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='country',
            field=models.CharField(blank=True, default='Italy', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='plan',
            field=models.CharField(choices=[('concierge', 'Digital Concierge — €25/mo'), ('checkin', 'Digital Check-In — €50/mo'), ('concierge_checkin', 'Concierge + Check-In — €75/mo'), ('full', 'Full Suite — €100/mo')], default='concierge', max_length=20),
        ),
    ]
