# Generated by Django 4.2.30 on 2026-08-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_update_plan_choices_add_country_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='plan',
            field=models.CharField(choices=[('concierge', 'Digital Concierge — £25/mo'), ('checkin', 'Digital Check-In — £50/mo'), ('concierge_checkin', 'Concierge + Check-In — £75/mo'), ('full', 'Full Suite — £100/mo')], default='concierge', max_length=20),
        ),
    ]
