"""
Management command: python manage.py seed_hotels
Seeds 5 London hotels + 15 Italian hotels (3 per city: Rome, Milan, Naples, Florence, Venice).
"""
from django.core.management.base import BaseCommand
from hotels.models import Hotel


HOTELS = [
    # ── UK — London (5) ─────────────────────────────────────────────────────
    {
        "name": "The Savoy",
        "city": "London",
        "country": "United Kingdom",
        "address": "Strand, London WC2R 0EU",
        "phone": "+44 20 7836 4343",
        "email": "info@thesavoy.com",
        "website": "https://www.thesavoy.com",
        "description": "One of London's most iconic luxury hotels, The Savoy has welcomed guests since 1889. Situated on the Strand, it offers stunning Thames River views, the legendary American Bar, and world-class dining.",
        "check_in_time": "15:00",
        "check_out_time": "12:00",
        "wifi_info": "The Savoy WiFi | Free for all guests",
        "is_24_7": True,
        "language_default": "en",
        "plan": "full",
        "is_verified": True,
        "amenities": ["Free WiFi", "Spa", "Gym", "Restaurant", "Bar", "Pool", "Room Service", "Concierge", "Business Center"],
    },
    {
        "name": "Claridge's Hotel",
        "city": "London",
        "country": "United Kingdom",
        "address": "Brook St, Mayfair, London W1K 4HR",
        "phone": "+44 20 7629 8860",
        "email": "info@claridges.co.uk",
        "website": "https://www.claridges.co.uk",
        "description": "A flagship art deco hotel in Mayfair, Claridge's has been the London address of royalty, heads of state, and celebrities for over a century. Its timeless elegance and exceptional service are unmatched.",
        "check_in_time": "14:00",
        "check_out_time": "12:00",
        "wifi_info": "Claridges-Guest | Available throughout",
        "is_24_7": True,
        "language_default": "en",
        "plan": "full",
        "is_verified": True,
        "amenities": ["Free WiFi", "Spa", "Restaurant", "Bar", "Room Service", "Concierge", "Business Center", "Laundry"],
    },
    {
        "name": "The Ritz London",
        "city": "London",
        "country": "United Kingdom",
        "address": "150 Piccadilly, St. James's, London W1J 9BR",
        "phone": "+44 20 7493 8181",
        "email": "enquire@theritzlondon.com",
        "website": "https://www.theritzlondon.com",
        "description": "The Ritz London is one of the world's most prestigious hotels, famous for its Louis XVI décor, afternoon tea, and the legendary Ritz Club casino. Located on Piccadilly, it epitomises British grandeur.",
        "check_in_time": "14:00",
        "check_out_time": "12:00",
        "wifi_info": "TheRitzLondon | Complimentary for guests",
        "is_24_7": True,
        "language_default": "en",
        "plan": "full",
        "is_verified": True,
        "amenities": ["Free WiFi", "Spa", "Restaurant", "Bar", "Room Service", "Concierge", "Laundry", "Business Center"],
    },
    {
        "name": "The Langham London",
        "city": "London",
        "country": "United Kingdom",
        "address": "1C Portland Pl, Regent St, London W1B 1JA",
        "phone": "+44 20 7636 1000",
        "email": "tllon.info@langhamhotels.com",
        "website": "https://www.langhamhotels.com/en/the-langham/london",
        "description": "Europe's first grand hotel, The Langham London opened in 1865 and continues to set the standard for luxury hospitality. Steps from Oxford Circus, its Artesian Bar is consistently ranked among the world's best.",
        "check_in_time": "15:00",
        "check_out_time": "12:00",
        "wifi_info": "Langham-Guest | Free high-speed WiFi",
        "is_24_7": True,
        "language_default": "en",
        "plan": "concierge_checkin",
        "is_verified": True,
        "amenities": ["Free WiFi", "Pool", "Spa", "Gym", "Restaurant", "Bar", "Room Service", "Concierge"],
    },
    {
        "name": "Hotel 41 London",
        "city": "London",
        "country": "United Kingdom",
        "address": "41 Buckingham Palace Rd, London SW1W 0PS",
        "phone": "+44 20 7300 0041",
        "email": "book@41hotel.com",
        "website": "https://www.41hotel.com",
        "description": "A boutique 5-star townhouse hotel opposite Buckingham Palace's Royal Mews. Hotel 41 offers black-and-white themed interiors, a dedicated butler service, and an exclusive lounge with complimentary treats.",
        "check_in_time": "14:00",
        "check_out_time": "12:00",
        "wifi_info": "Hotel41 | Complimentary unlimited WiFi",
        "is_24_7": False,
        "language_default": "en",
        "plan": "concierge_checkin",
        "is_verified": True,
        "amenities": ["Free WiFi", "Bar", "Room Service", "Concierge", "Laundry", "Business Center"],
    },

    # ── Italy — Rome (3) ─────────────────────────────────────────────────────
    {
        "name": "Hotel de Russie",
        "city": "Rome",
        "country": "Italy",
        "address": "Via del Babuino, 9, 00187 Roma RM",
        "phone": "+39 06 328881",
        "email": "hotel.derussie@roccofortecollection.com",
        "website": "https://www.roccofortecollection.com/hotels/hotel-de-russie",
        "description": "A Rocco Forte hotel nestled between the Spanish Steps and Piazza del Popolo, Hotel de Russie offers a serene garden terrace, luxurious spa, and the legendary Bar Stravinskij beloved by artists and celebrities since the 1800s.",
        "check_in_time": "15:00",
        "check_out_time": "12:00",
        "wifi_info": "deRussie | Free WiFi for all guests",
        "is_24_7": True,
        "language_default": "it",
        "plan": "full",
        "is_verified": True,
        "amenities": ["Free WiFi", "Pool", "Spa", "Gym", "Restaurant", "Bar", "Room Service", "Concierge", "Garden", "Terrace"],
    },
    {
        "name": "Borghese Palace Art Hotel",
        "city": "Rome",
        "country": "Italy",
        "address": "Via Purificazione, 4, 00187 Roma RM",
        "phone": "+39 06 42112243",
        "email": "info@borghesepalace.it",
        "website": "https://www.borghesepalace.it",
        "description": "A boutique art hotel steps from the Borghese Gallery and Via Veneto. Each room is individually designed with original artworks, offering an intimate and culturally rich stay in the heart of Rome.",
        "check_in_time": "14:00",
        "check_out_time": "11:00",
        "wifi_info": "BorghesePalace-WiFi | Gratuito",
        "is_24_7": False,
        "language_default": "it",
        "plan": "concierge",
        "is_verified": True,
        "amenities": ["Free WiFi", "Bar", "Concierge", "Air Conditioning", "City View"],
    },
    {
        "name": "The First Roma Arte",
        "city": "Rome",
        "country": "Italy",
        "address": "Via del Vantaggio, 14, 00186 Roma RM",
        "phone": "+39 06 45617070",
        "email": "info@thefirstroma.com",
        "website": "https://www.thefirstroma.com",
        "description": "A luxury design hotel near the Piazza del Popolo, The First Roma Arte showcases a permanent collection of contemporary Italian art. Rooftop terrace with panoramic views of Rome and a celebrated restaurant.",
        "check_in_time": "14:00",
        "check_out_time": "12:00",
        "wifi_info": "TheFirstRoma | Gratuito",
        "is_24_7": True,
        "language_default": "it",
        "plan": "concierge_checkin",
        "is_verified": True,
        "amenities": ["Free WiFi", "Restaurant", "Bar", "Spa", "Terrace", "City View", "Concierge", "Air Conditioning"],
    },

    # ── Italy — Milan (3) ────────────────────────────────────────────────────
    {
        "name": "Bulgari Hotel Milano",
        "city": "Milan",
        "country": "Italy",
        "address": "Via Privata Fratelli Gabba, 7b, 20121 Milano MI",
        "phone": "+39 02 805805",
        "email": "milan@bulgarihotels.com",
        "website": "https://www.bulgarihotels.com/milan",
        "description": "Set in a historic palace in the Golden Triangle, Bulgari Hotel Milano is a temple of contemporary Italian design. Its private garden, acclaimed restaurant, and spa make it one of Milan's most exclusive addresses.",
        "check_in_time": "15:00",
        "check_out_time": "12:00",
        "wifi_info": "Bulgari-Milan | Complimentary",
        "is_24_7": True,
        "language_default": "it",
        "plan": "full",
        "is_verified": True,
        "amenities": ["Free WiFi", "Pool", "Spa", "Gym", "Restaurant", "Bar", "Room Service", "Concierge", "Garden", "Business Center"],
    },
    {
        "name": "Mandarin Oriental Milan",
        "city": "Milan",
        "country": "Italy",
        "address": "Via Andegari, 9, 20121 Milano MI",
        "phone": "+39 02 8731 8888",
        "email": "momil-reservations@mohg.com",
        "website": "https://www.mandarinoriental.com/en/milan/via-andegari",
        "description": "Five restored 18th-century townhouses create the Mandarin Oriental Milan, offering an intimate yet grand atmosphere in the heart of the fashion district. The Michelin-starred Seta restaurant and Mandarin Spa are highlights.",
        "check_in_time": "15:00",
        "check_out_time": "12:00",
        "wifi_info": "MO-Milan-Guest | Gratuito",
        "is_24_7": True,
        "language_default": "it",
        "plan": "full",
        "is_verified": True,
        "amenities": ["Free WiFi", "Spa", "Restaurant", "Bar", "Room Service", "Concierge", "Laundry"],
    },
    {
        "name": "Palazzo Parigi Hotel & Grand Spa",
        "city": "Milan",
        "country": "Italy",
        "address": "Corso di Porta Nuova, 1, 20121 Milano MI",
        "phone": "+39 02 625625",
        "email": "info@palazzoparigi.com",
        "website": "https://www.palazzoparigi.com",
        "description": "An extraordinary palazzo hotel near the Brera art district, Palazzo Parigi blends 18th-century architecture with contemporary luxury. The grand spa and rooftop pool make it a sanctuary in the city centre.",
        "check_in_time": "14:00",
        "check_out_time": "12:00",
        "wifi_info": "PalazzoParigi | WiFi gratuito",
        "is_24_7": True,
        "language_default": "it",
        "plan": "concierge_checkin",
        "is_verified": True,
        "amenities": ["Free WiFi", "Pool", "Spa", "Gym", "Restaurant", "Bar", "Room Service", "Concierge", "City View"],
    },

    # ── Italy — Naples (3) ───────────────────────────────────────────────────
    {
        "name": "Grand Hotel Vesuvio",
        "city": "Naples",
        "country": "Italy",
        "address": "Via Partenope, 45, 80121 Napoli NA",
        "phone": "+39 081 7640044",
        "email": "info@vesuvio.it",
        "website": "https://www.vesuvio.it",
        "description": "Overlooking the Bay of Naples with Vesuvius as a backdrop, the Grand Hotel Vesuvio has welcomed nobility, artists, and world leaders since 1882. Its rooftop restaurant Caruso is one of the most romantic settings in Italy.",
        "check_in_time": "15:00",
        "check_out_time": "12:00",
        "wifi_info": "Vesuvio-Guest | WiFi gratuito",
        "is_24_7": True,
        "language_default": "it",
        "plan": "full",
        "is_verified": True,
        "amenities": ["Free WiFi", "Pool", "Spa", "Restaurant", "Bar", "Room Service", "Concierge", "Sea View", "Terrace"],
    },
    {
        "name": "Hotel Romeo",
        "city": "Naples",
        "country": "Italy",
        "address": "Via Cristoforo Colombo, 45, 80133 Napoli NA",
        "phone": "+39 081 017 5001",
        "email": "romeo@romeohotel.it",
        "website": "https://www.romeohotel.it",
        "description": "A contemporary architectural masterpiece on the port of Naples, Hotel Romeo offers panoramic views of Vesuvius and Capri. Designed by Kenzo Tange, it features a Michelin-starred rooftop restaurant and a full-floor spa.",
        "check_in_time": "15:00",
        "check_out_time": "12:00",
        "wifi_info": "Romeo-Hotel | Gratuito",
        "is_24_7": True,
        "language_default": "it",
        "plan": "concierge_checkin",
        "is_verified": True,
        "amenities": ["Free WiFi", "Pool", "Spa", "Gym", "Restaurant", "Bar", "Room Service", "Sea View", "Concierge"],
    },
    {
        "name": "Costantinopoli 104",
        "city": "Naples",
        "country": "Italy",
        "address": "Via Santa Maria di Costantinopoli, 104, 80138 Napoli NA",
        "phone": "+39 081 5571035",
        "email": "info@costantinopoli104.it",
        "website": "https://www.costantinopoli104.it",
        "description": "A charming boutique hotel set in a 19th-century liberty villa in the historic centre of Naples. With a beautiful garden and pool, Costantinopoli 104 offers a peaceful escape just steps from the National Archaeological Museum.",
        "check_in_time": "14:00",
        "check_out_time": "11:00",
        "wifi_info": "Costantinopoli104 | Gratuito",
        "is_24_7": False,
        "language_default": "it",
        "plan": "concierge",
        "is_verified": True,
        "amenities": ["Free WiFi", "Pool", "Garden", "Bar", "Concierge", "Air Conditioning"],
    },

    # ── Italy — Florence (3) ─────────────────────────────────────────────────
    {
        "name": "Four Seasons Hotel Firenze",
        "city": "Florence",
        "country": "Italy",
        "address": "Borgo Pinti, 99, 50121 Firenze FI",
        "phone": "+39 055 2626 1",
        "email": "reservations.firenze@fourseasons.com",
        "website": "https://www.fourseasons.com/florence",
        "description": "Spanning two Renaissance palaces and 11 acres of private gardens, the Four Seasons Florence is a legendary destination. With Michelangelo-frescoed ceilings and unrivalled gardens in the heart of the city.",
        "check_in_time": "15:00",
        "check_out_time": "12:00",
        "wifi_info": "FourSeasonsFI | Gratuito",
        "is_24_7": True,
        "language_default": "it",
        "plan": "full",
        "is_verified": True,
        "amenities": ["Free WiFi", "Pool", "Spa", "Gym", "Restaurant", "Bar", "Room Service", "Concierge", "Garden", "Business Center"],
    },
    {
        "name": "Hotel Brunelleschi Firenze",
        "city": "Florence",
        "country": "Italy",
        "address": "Piazza Santa Elisabetta, 3, 50122 Firenze FI",
        "phone": "+39 055 27370",
        "email": "info@hotelbrunelleschi.it",
        "website": "https://www.hotelbrunelleschi.it",
        "description": "A unique hotel built within a 6th-century Byzantine tower in the medieval core of Florence. The Brunelleschi's museum houses artefacts found during restoration, and its Michelin-starred restaurant Santa Elisabetta is celebrated worldwide.",
        "check_in_time": "14:00",
        "check_out_time": "12:00",
        "wifi_info": "Brunelleschi-WiFi | Gratuito",
        "is_24_7": True,
        "language_default": "it",
        "plan": "concierge_checkin",
        "is_verified": True,
        "amenities": ["Free WiFi", "Restaurant", "Bar", "Spa", "Concierge", "City View", "Air Conditioning"],
    },
    {
        "name": "Soprarno Suites",
        "city": "Florence",
        "country": "Italy",
        "address": "Via Maggio, 35, 50125 Firenze FI",
        "phone": "+39 055 046 8558",
        "email": "info@soprarnos.com",
        "website": "https://www.soprarnos.com",
        "description": "A beautifully curated boutique property in the artistic Oltrarno district, across the Ponte Vecchio. Soprarno Suites feels like staying in a Florentine friend's apartment — full of art, books, and crafted antiques.",
        "check_in_time": "14:00",
        "check_out_time": "11:00",
        "wifi_info": "SoprArno | Gratuito",
        "is_24_7": False,
        "language_default": "it",
        "plan": "concierge",
        "is_verified": True,
        "amenities": ["Free WiFi", "Concierge", "Air Conditioning", "Garden"],
    },

    # ── Italy — Venice (3) ───────────────────────────────────────────────────
    {
        "name": "Hotel Danieli Venice",
        "city": "Venice",
        "country": "Italy",
        "address": "Castello, 4196, 30122 Venezia VE",
        "phone": "+39 041 5226480",
        "email": "danieli@luxurycollection.com",
        "website": "https://www.hoteldanieli.com",
        "description": "Housed in a 14th-century Gothic palace overlooking the lagoon, Hotel Danieli is Venice's most storied address. Favoured by George Sand, Dickens and Wagner, its rooftop restaurant offers unparalleled views of the Doge's Palace.",
        "check_in_time": "15:00",
        "check_out_time": "12:00",
        "wifi_info": "Danieli-Guest | Gratuito",
        "is_24_7": True,
        "language_default": "it",
        "plan": "full",
        "is_verified": True,
        "amenities": ["Free WiFi", "Restaurant", "Bar", "Spa", "Room Service", "Concierge", "Sea View", "Terrace"],
    },
    {
        "name": "Aman Venice",
        "city": "Venice",
        "country": "Italy",
        "address": "Calle Tiepolo, 1364, 30125 Venezia VE",
        "phone": "+39 041 270 7333",
        "email": "venice@aman.com",
        "website": "https://www.aman.com/hotels/aman-venice",
        "description": "A 16th-century palazzo on the Grand Canal, Aman Venice occupies one of the grandest private residences in the city. With just 24 suites, it offers an extraordinarily intimate experience surrounded by frescoes, silk-hung walls, and Murano chandeliers.",
        "check_in_time": "15:00",
        "check_out_time": "12:00",
        "wifi_info": "Aman-Venice | Gratuito per tutti",
        "is_24_7": True,
        "language_default": "it",
        "plan": "full",
        "is_verified": True,
        "amenities": ["Free WiFi", "Pool", "Spa", "Restaurant", "Bar", "Room Service", "Concierge", "Sea View", "Garden"],
    },
    {
        "name": "Palazzina G Venice",
        "city": "Venice",
        "country": "Italy",
        "address": "San Polo, 901, 30125 Venezia VE",
        "phone": "+39 041 5284644",
        "email": "info@palazzinag.com",
        "website": "https://www.palazzinag.com",
        "description": "A boutique hotel by French designer Philippe Starck, Palazzina G brings modern glamour to a 15th-century Venetian palace on the Grand Canal. Vibrant interiors, a lively bar, and a roof terrace overlooking the rooftops of Venice.",
        "check_in_time": "14:00",
        "check_out_time": "12:00",
        "wifi_info": "PalazzinaG | WiFi gratuito",
        "is_24_7": False,
        "language_default": "it",
        "plan": "concierge_checkin",
        "is_verified": True,
        "amenities": ["Free WiFi", "Bar", "Concierge", "Sea View", "Terrace", "Air Conditioning"],
    },
]


class Command(BaseCommand):
    help = "Seed 20 real hotels (5 London + 15 Italy) into the database"

    def handle(self, *args, **options):
        created = 0
        skipped = 0
        for data in HOTELS:
            amenities = data.pop("amenities", [])
            hotel, is_new = Hotel.objects.get_or_create(
                name=data["name"],
                city=data["city"],
                defaults={**data, "amenities": amenities},
            )
            if is_new:
                hotel.amenities = amenities
                hotel.save(update_fields=["amenities"])
                created += 1
                self.stdout.write(self.style.SUCCESS(f"  Created: {hotel.name} ({hotel.city})"))
            else:
                # Update existing with fresh data
                for k, v in data.items():
                    setattr(hotel, k, v)
                hotel.amenities = amenities
                hotel.save()
                skipped += 1
                self.stdout.write(f"  Updated: {hotel.name} ({hotel.city})")

        self.stdout.write(self.style.SUCCESS(f"\nDone — {created} created, {skipped} updated."))
