# Generated by Django 4.2.30 on 2026-06-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('museum', 'Museum'), ('cafe', 'Cafe'), ('attraction', 'Attraction'), ('shop', 'Shop'), ('parking', 'Parking'), ('nightlife', 'Night Life'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
