# Generated by Django 4.2.30 on 2026-05-08 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('language_default', models.CharField(choices=[('en', 'English'), ('it', 'Italian'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish')], default='en', max_length=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hotel-logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
