# Generated by Django 4.2.30 on 2026-05-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_in_time',
            field=models.CharField(blank=True, default='14:00', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_time',
            field=models.CharField(blank=True, default='11:00', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hotel',
            name='wifi_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
