# Generated by Django 4.2.30 on 2026-05-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_add_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='close_time',
            field=models.CharField(blank=True, default='22:00', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_24_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='open_time',
            field=models.CharField(blank=True, default='09:00', max_length=10),
        ),
    ]
