# Generated by Django 4.2.30 on 2026-07-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_add_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='language_default',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italian'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], default='en', max_length=5),
        ),
    ]
