# Generated by Django 4.2.30 on 2026-08-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_outreach_trial_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteloutreach',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano')], default='en', max_length=5),
        ),
    ]
