# Generated by Django 4.2.30 on 2026-08-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_alter_hotel_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
