# Generated by Django 4.2.30 on 2026-09-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_hotel_is_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description_es',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_it',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
